version: "2.1"

services:
 nginx:
   build: ./nginx/
   ports:
     - 80:80
   volumes:
     - "${PROJECT_ROOT}:/var/www/html"
   depends_on:
     - php

 php:
   build: ./php/
   expose:
     - 9000
   volumes:
     - "${PROJECT_ROOT}:/var/www/html"
   depends_on:
     - mysql

 mysql:
   image: mysql:latest
   volumes:
     - data:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
     MYSQL_DATABASE: "${DB_NAME}"
     MYSQL_USER: "${DB_USERNAME}"
     MYSQL_PASSWORD: "${DB_PASSWORD}"

volumes:
 data:
